[package]
name = "service"
edition.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true }
database = { path = "../database" }
common = { path = "../common" }
sqlx = { workspace = true }
