[package]
name = "database"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
sqlx = { workspace = true }
chrono = { workspace = true }
common = { path = "../common" }
serde = { workspace = true }
utils = { path = "../utils" }
