[package]
name = "setting"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
config = { workspace = true }
tokio = { workspace = true }
sea-orm = { workspace = true }
