[package]
name = "api"
edition.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
service = { path = "../service" }
tower-http = { workspace = true }
tower = { workspace = true }
sea-orm = { workspace = true }
